export const WINDOW_FRAME_INSET = 8;
export const WINDOW_TRAFFIC_LIGHT_DIAMETER = 14;
export const WINDOW_TRAFFIC_LIGHT_OFFSET = { x: 18, y: 21 } as const;
export const WINDOW_TRAFFIC_LIGHT_CENTER_Y =
	WINDOW_TRAFFIC_LIGHT_OFFSET.y + WINDOW_TRAFFIC_LIGHT_DIAMETER / 2;
export const WINDOW_TOP_CONTROL_SIZE = 36;
export const WINDOW_TOP_CONTROL_TOP = WINDOW_TRAFFIC_LIGHT_CENTER_Y - WINDOW_TOP_CONTROL_SIZE / 2;
export const WINDOW_TOP_BAR_HEIGHT = WINDOW_TRAFFIC_LIGHT_CENTER_Y * 2;
